blank_issues_enabled: false
contact_links:
  - name: CHRONODESK Discussions
    url: https://github.com/mrmedani/chronodesk/discussions
    about: Please ask questions and discuss ideas here
  - name: Security Policy
    url: https://github.com/mrmedani/chronodesk/security/policy
    about: Report security vulnerabilities here
